[package]
name = "boxpub"
version = "3.0.0"
authors = [ "Edmund Wu" ]
license = "AGPL-3.0"

edition = "2018"

[[bin]]
name = "boxpub"
path = "src/main.rs"

[lib]
name = "boxpub"
crate-type = [ "cdylib" ]

[dependencies]
pyo3 = "0.10.1"
structopt = "0.3.14"
